### ISSUE TITLE
HttpException`1: HTTP/1.1 403 Forbidden

### ISSUE THREAD

**Issue by yucelz** [Unity-Technologies/com.unity.services.samples.game-lobby#19]
HttpException`1: HTTP/1.1 403 Forbidden
Unity.Services.Lobbies.Http.ResponseHandler.HandleAsyncResponse (Unity.Services.Lobbies.Http.HttpClientResponse response, System.Collections.Generic.Dictionary`2[TKey,TValue] statusCodeToTypeMap) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Http/ResponseHandler.cs:103)
Unity.Services.Lobbies.Http.ResponseHandler.HandleAsyncResponse[T] (Unity.Services.Lobbies.Http.HttpClientResponse response, System.Collections.Generic.Dictionary`2[TKey,TValue] statusCodeToTypeMap) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Http/ResponseHandler.cs:186)
Unity.Services.Lobbies.Apis.Lobby.LobbyApiClient+<GetLobbyAsync>d__9.MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Apis/LobbyApi.cs:305)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Unity.Services.Lobbies.WrappedLobbyService+<TryCatchRequest>d__18`2[TRequest,TReturn].MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:194)
Rethrow as LobbyServiceException: An unknown error occurred
Unity.Services.Lobbies.WrappedLobbyService.ResolveErrorWrapping (Unity.Services.Lobbies.LobbyExceptionReason reason, System.Exception exception) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:249)
Unity.Services.Lobbies.WrappedLobbyService+<TryCatchRequest>d__18`2[TRequest,TReturn].MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:198)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Unity.Services.Lobbies.WrappedLobbyService+<GetLobbyAsync>d__7.MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:60)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:33)
Rethrow as Exception: Call stack before async call:
System.Environment.get_StackTrace () (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:31)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest.DoRequest[T] (System.Threading.Tasks.Task`1[TResult] task, System.Action`1[T] onComplete) (at <b3115f6673e144c7b127570f243d0d0c>:0)
LobbyRelaySample.lobby.LobbyAPIInterface.GetLobbyAsync (System.String lobbyId, System.Action`1[T] onComplete) (at Assets/Scripts/Lobby/LobbyAPIInterface.cs:78)
LobbyRelaySample.LobbyAsyncRequests.RetrieveLobbyAsync (System.String lobbyId, System.Action`1[T] onComplete) (at Assets/Scripts/Lobby/LobbyAsyncRequests.cs:233)
LobbyRelaySample.LobbyAsyncRequests.UpdateLobby (System.Single unused) (at Assets/Scripts/Lobby/LobbyAsyncRequests.cs:55)
LobbyRelaySample.UpdateSlow.OnUpdate (System.Single dt) (at Assets/Scripts/Infrastructure/UpdateSlow.cs:99)
LobbyRelaySample.UpdateSlow.Update () (at Assets/Scripts/Infrastructure/UpdateSlow.cs:69)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:39)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <ad3eaa0878d94cbe8e45f9c494d71647>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
LobbyRelaySample.LogHandler:LogException(Exception, Object) (at Assets/Scripts/Infrastructure/LogHandler.cs:60)
UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Comment by RR7** [comment]
i also have this issue. :\

**Comment by Nevey** [comment]
Similar issue when trying to join lobby:

```
HttpException`1: HTTP/1.1 403 Forbidden
Unity.Services.Lobbies.Http.ResponseHandler.HandleAsyncResponse (Unity.Services.Lobbies.Http.HttpClientResponse response, System.Collections.Generic.Dictionary`2[TKey,TValue] statusCodeToTypeMap) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Http/ResponseHandler.cs:95)
Unity.Services.Lobbies.Http.ResponseHandler.HandleAsyncResponse[T] (Unity.Services.Lobbies.Http.HttpClientResponse response, System.Collections.Generic.Dictionary`2[TKey,TValue] statusCodeToTypeMap) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Http/ResponseHandler.cs:186)
Unity.Services.Lobbies.Apis.Lobby.LobbyApiClient+<CreateLobbyAsync>d__6.MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/Apis/LobbyApi.cs:224)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Unity.Services.Lobbies.WrappedLobbyService+<TryCatchRequest>d__18`2[TRequest,TReturn].MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:194)
Rethrow as LobbyServiceException: An unknown error occurred
Unity.Services.Lobbies.WrappedLobbyService.ResolveErrorWrapping (Unity.Services.Lobbies.LobbyExceptionReason reason, System.Exception exception) (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:244)
Unity.Services.Lobbies.WrappedLobbyService+<TryCatchRequest>d__18`2[TRequest,TReturn].MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:198)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
Unity.Services.Lobbies.WrappedLobbyService+<CreateLobbyAsync>d__4.MoveNext () (at Library/PackageCache/com.unity.services.lobby@1.0.0-pre.6/Runtime/SDK/WrappedLobbyService.cs:39)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:33)
Rethrow as Exception: Call stack before async call:
System.Environment.get_StackTrace () (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:31)
System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine] (TStateMachine& stateMachine) (at <695d1cc93cca45069c528c15c9fdd749>:0)
LobbyRelaySample.AsyncRequest.DoRequest[T] (System.Threading.Tasks.Task`1[TResult] task, System.Action`1[T] onComplete) (at <610fb17972374768b3251deeb3cacee6>:0)
LobbyRelaySample.lobby.LobbyAPIInterface.CreateLobbyAsync (System.String requesterUASId, System.String lobbyName, System.Int32 maxPlayers, System.Boolean isPrivate, System.Collections.Generic.Dictionary`2[TKey,TValue] localUserData, System.Action`1[T] onComplete) (at Assets/Scripts/Lobby/LobbyAPIInterface.cs:23)
LobbyRelaySample.LobbyAsyncRequests.CreateLobbyAsync (System.String lobbyName, System.Int32 maxPlayers, System.Boolean isPrivate, LobbyRelaySample.LobbyUser localUser, System.Action`1[T] onSuccess, System.Action onFailure) (at Assets/Scripts/Lobby/LobbyAsyncRequests.cs:121)
LobbyRelaySample.GameManager.OnReceiveMessage (LobbyRelaySample.MessageType type, System.Object msg) (at Assets/Scripts/Game/GameManager.cs:101)
LobbyRelaySample.Messenger.OnReceiveMessage (LobbyRelaySample.MessageType type, System.Object msg) (at Assets/Scripts/Infrastructure/Messenger.cs:41)
LobbyRelaySample.UI.CreateMenuUI.OnCreatePressed () (at Assets/Scripts/UI/CreateMenuUI.cs:30)
UnityEngine.Events.InvokableCall.Invoke () (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.UI.Button.Press () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:70)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/UI/Core/Button.cs:114)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:57)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/ExecuteEvents.cs:272)
UnityEngine.EventSystems.StandaloneInputModule.ReleaseMouse (UnityEngine.EventSystems.PointerEventData pointerEvent, UnityEngine.GameObject currentOverGo) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:190)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMousePress (UnityEngine.EventSystems.PointerInputModule+MouseButtonEventData data) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:640)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent (System.Int32 id) (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:546)
UnityEngine.EventSystems.StandaloneInputModule.ProcessMouseEvent () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:526)
UnityEngine.EventSystems.StandaloneInputModule.Process () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/InputModules/StandaloneInputModule.cs:280)
UnityEngine.EventSystems.EventSystem.Update () (at Library/PackageCache/com.unity.ugui@1.0.0/Runtime/EventSystem/EventSystem.cs:501)
LobbyRelaySample.AsyncRequest+<DoRequest>d__1`1[T].MoveNext () (at Assets/Scripts/Infrastructure/AsyncRequest.cs:39)
--- End of stack trace from previous location where exception was thrown ---
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <695d1cc93cca45069c528c15c9fdd749>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <41d34619c06946aebeba0ca1ee6d765b>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
LobbyRelaySample.LogHandler:LogException(Exception, Object) (at Assets/Scripts/Infrastructure/LogHandler.cs:60)
```

**Comment by RR7** [comment]
it seems after you link the project to the UGS, you have to go to the section in lobby and relay that says 'getting started' follow it though and make sure to compete step 3 called activate service. then this section changes to have an on/off switch for relay and lobby, which should be on.

i did this and the project works, so its not actually an issue with this project.

**Comment by Nevey** [comment]
> it seems after you link the project to the UGS, you have to go to the section in lobby and relay that says 'getting started' follow it though and make sure to compete step 3 called activate service. then this section changes to have an on/off switch for relay and lobby, which should be on.
> 
> i did this and the project works, so its not actually an issue with this project.

This did not work for me, as I had already done this and tried the same with several test projects for several different organizations linked to my account. Now the project also started crashing on play so I'll do a clean checkout. I'm using Unity 2021.1.22f1

**Comment by Nevey** [comment]
Finally managed to get it to work by using Unity 2020.3.20f1
 

- Automatically create a new project under Project Settings -> Services
- Assets -> Reimport All

Connecting or creating a lobby does not give any issues now.

However, it does seem the tool has some issues under the hood when using the wizard and/or not setting up your project before correctly (enabling Lobby and Relay) and/or using a newer version of Unity.

**Comment by nathaniel-buck** [comment]
RR7 is correct about the need to complete the Lobby and Relay setup in the dashboard to get past the `403` errors. A `401` pertains to an Authentication error, which you'll get if your project ID hasn't been linked.

We're keeping the sample on the 2020 LTS (2020.3.20f1 at the moment) since we know each of the services will work as released on that version, so no guarantees that it will work on 2021.x.

**Comment by rocuh** [comment]
Had a quick play with this, having same issues. Using 2020.3.20f1, just seems intermitent, sometimes it works without any 403 error messages, sometimes it popups one 403 error, sometimes it spams the 403s although its still kind of working. Something connected to latency somewhere maybe?

**Comment by rocuh** [comment]
follow up - its been fine now. I think you just have to wait a while after toggling the setting on the dashboard. I assume there are multiple servers on unitys end ? Perhaps it just takes a while for the permission to be replicated to all the lobby/relay servers.
