### ISSUE TITLE
Connecting....

### ISSUE THREAD

**Issue by yucelz** [Unity-Technologies/com.unity.services.samples.game-lobby#20]
Hi team;
1-) I can able to create a new  Lobby
2-)  The owner of the Lobby can able to enter the "In Lobby" stage
3-) 2nd user stuck in the "Connecting..." state 

First question: Is there any daily limit on Relay connections?
Second: Where can we able to manage unused and old sessions in the Relay (like deleting old relay sessions from the dashboard )
![Screenshot (3)](https://user-images.githubusercontent.com/3542321/140649507-8ed76070-86b1-467e-8e90-2cdbca543f18.png)

**Comment by nathaniel-buck** [comment]
There should be a timeout after a few seconds of being stuck "Connecting..." and then the client returns to the menu, where they could try to reconnect.
There's no daily limit on Relay connections that I've encountered, no.
All cleanup of old lobbies or Relay allocations is handled on the side of the service, so there should be no need to manage old sessions.
