### ISSUE TITLE
The code doesn't seem very understandable for n00bs like me

### ISSUE THREAD

**Issue by RR7** [Unity-Technologies/com.unity.services.samples.game-lobby#22]
i discussed this in the discord and it was suggested I post my opinion here as feedback. So having come from HLAPI, I'm trying to work out how lobby works and if i need it and how best to use it, since currently the Boss Room sample does not use this.

the problem i seem to have is that I've never seen this 'observer pattern' style code before. the only observer pattern experience i've had until today was watching Fringe on TV.

No unity sample I've seen before uses this. my HLAPI project certainly isn't written this way. the Hello World sample isn't written this way either.

Rather then looking at this sample and seeing how to use Lobby, I find myself heaving to try learn how what its actually going on, what a lot of the shorthand code means, and how this might work if i don't follow this pattern.

I'm not a great coder, i get by in scripts, that's why I use unity, great coders have already done their magic to make it do stuff for me. 

I'm not in any way suggesting what's here is wrong. just maybe its too good for basic folk like me to make sense of. 

and so that's my feedback, please close this as soon as its been read.

**Comment by UnityJacob** [comment]
Hi RR7!
This is great feedback! We do want to help bridge the gap between the hello world samples and scalable game production, and this sample was an attempt at that. 

In this case we made design decisions close to how we would have if we were building a game to scale on top of the lobby and relay system.

You're absolutely right that the Observer pattern does break typical unity code following via references, and it will be worthwhile for us to take a look at adding comments and maybe restructuring to help step users through the processes.

If it's cool with you, I'd like to keep the thread open while we do some iteration on the project to help make it clearer.

**Comment by RR7** [comment]
sure thanks for reading :) I do feel, that if the separate groups such as networking, lobby, MLAPI, boss room, even the inputsystem/warrior demo folk could come together and create a great standard for all this to work, it would be awesome. 'this is how you do it, and its good' is an awesome thing that would mean we can spend the time creating great games that work this way and not dying in code limbo :)

**Comment by rodellison** [comment]
Found myself stopping by and agreeing totally with the @RR7 on this.. Have just started my Netcode multiplayer journey and am definitely struggling a little. Followed some of DilmerV's youtubes to get a decent handle on using Relay for a jump right in Host/Client relay type of room, and was also able to mostly understand the general flow of BossRoom which seems to setup a pseudo private lobby in it's main and charselect scenes before all ready-up and transition to the game scene.  I think what's losing me in **_this_** lobby focused repo demo is the higher amount of obfuscation I find myself trying to understand, as opposed to understanding how the actual Lobby/Relay mechanics work.

A suggestion, humbly asking since the multiplayer topic (and especially organizing game lobby) is tough enough without also having to get well versed on a particular nuance of game design pattern (observer), I'm wondering if it might be possible to somehow create something a bit even more barebones that bridges the two projects (not the full game of BossRoom), but rather, a demo that uses the BossRoom scene progression type flow which 'seems' pretty easy to understand (but where a public Lobby is established where all can ready up prior to starting the game.

**Comment by UnityJacob** [comment]
Thank you for the feedback! 
In general we agree with making another pass on the lobby-relay sample to make it easier to understand. Comments like these are valuable as we go towards updating the project.

To confirm my understanding, by
`BossRoom scene progression type flow `
you mean it would be easier to read a project that was split into bespoke scenes?
So for this sample, it would be three scenes arranged like:

1. mainMenu
2. Lobby
3. Game

?

**Comment by rodellison** [comment]
@UnityJacob, thanks!, and yes - that's the flow I'm thinking of..  I think BossRoom has its first scene as 'Startup' where its fairly easy to understand that it sets up a couple of 'dontdestroy' type objects, but then (using its StartupRoot object), immediately scene loads the MainMenu Scene, where the main networking stuff gets presented to the user.  Perhaps its there that the Lobby work happens, and then (after sync up), moving on to the Game..

**Comment by Jice128** [comment]
> Thank you for the feedback! In general we agree with making another pass on the lobby-relay sample to make it easier to understand. Comments like these are valuable as we go towards updating the project.
> 
> To confirm my understanding, by `BossRoom scene progression type flow ` you mean it would be easier to read a project that was split into bespoke scenes? So for this sample, it would be three scenes arranged like:
> 
>     1. mainMenu
> 
>     2. Lobby
> 
>     3. Game
> 
> 
> ?

im agreed with previous. I may tell parallel with photon or mirrom. 
for example demo with rooms.
I need create room -
using pun
photon.network.create room()
roomname ="bla bla bla"
or
room_id = "283727272"
so on

I liked very much unity networking, but I think creating games need to be easy, and on this demo I see how one instance, watching for another instance, been watched by another instance... 
I just want to know
- how creating rooms
- how I may give ID to rooms
- how I may "reading" id of connected people. 
- how create may be another room on server or
- how create dedicated server room(hot host  -> client)
 and so on.. sorry for such list, but im really think that unity is the best  engine, and it can give opportunity to create games for every one.

**Comment by Zarkaoui** [comment]
@UnityJacob 
Hello everyone !

I also have to agree with @RR7 . I'm a total beginner with Unity/C# and this sample & the boss room both look so out of league for me that it's really discouraging.
In this sample project there are 90 scripts in a single scene and I can't understand the structure/logic of the project...

2 years ago or so I could easily set up a lobby + multiplayer game scene using PUN2 by simply following some easy to understand tutorials.
When I heard the news about Netcode for GameObject I decided to go back to Unity but then it seems WAY more difficult to set up.

Don't get me wrong, I love what you are doing at Unity and it's great that you finally decided for a Network solution, but then you should make it really simple to use. The whole purpose of having all these extra services around Netcode for GameObject (Relay,  Vivox, Lobby etc...) should be to simplify things, not making it super hard to understand/use.

**Comment by UnityJacob** [comment]
@Zarkaoui 
Hello! Apologies for my absence! I want to just do an update on where we are at.

The underlying problem we are all having is that where PUN and Photon are more inclusive multiplayer packages, Unity is going for a strategy of separating the individual services and features that make up multiplayer gaming into individual packages, allowing users to pick and choose what services of ours they want to use, in combination with ones they bring themselves. 

We are currently figuring out how we want to deliver the user experiences closer to that of our third party solutions like PUN and Photon, allowing anyone to get up and running quickly with Multiplayer in Unity.

I'm working on the Lobby sample at the moment with this feedback In mind and I'll keep you posted when there is something to share. (Soon!)

**Comment by UnityJacob** [comment]
@Zarkaoui @RR7 @rodellison @Jice128 
I'm going to close this with an Update! We just pushed a major rework of the structure, along with an update to how Lobby receives updates from the service. Check out the Changelog.md for more detail. 

I hope you'll give it another shot and please do let me know what you think of it now.

**Comment by Zarkaoui** [comment]
Thanks a lot for the feedback @UnityJacob  !!!
I'll definitely take a look at the new code !
Thanks to all the Unity staff doing a great work at helping the community !

**Comment by RScanlan1990** [comment]
I have been trying to understand the example for a full day. I still think the use of LobbyEventCallbacks is too complex for a novice especially considering the documentation doesn't mention it as far as I can see, how comes there isn't a version that uses a polling loop?
