### ISSUE TITLE
Failed to find any open lobbies

### ISSUE THREAD

**Issue by Jice128** [Unity-Technologies/com.unity.services.samples.game-lobby#27]
Hi all! Just downloaded project. Created some lobby rooms and I cant join them on same PC. It this bug? From youtube video it should we fine. From different PC on same LAN or internet it connected well. But not on one PC

**Comment by UnityJacob** [comment]
Hi, apologies for the late reply, you are right that this should work and I am back on the project to fix issues and address feedback.

I'll follow up in this thread when I have. a fix.
