### ISSUE TITLE
Nonstop error popups

### ISSUE THREAD

**Issue by IAmTerrific** [Unity-Technologies/com.unity.services.samples.game-lobby#28]
On opening project, error window pops up saying: "A GameObject cannot have both a NetworkManager and NetworkObject assigned to it or any children under it."

Source of error is in prefab with NetworkManager script as well as a NetworkGameobject script on a child object. It attempts to delete the offensive object, but since its protected in a prefab it is unable to.

Placing the prefab in scene and unpacking results in the same error prompt as above, but it succeeds in removing the network object. However, the InGameRunner script detects that there is no networkgameobject script and prompts to add it with 3 options. 
-- Yes - which adds the script, then promptly gets it removed leading to the same 3 options.
-- No (add manually) - which apparently does nothing as the 3 option prompt reappears immediately.
-- Yes (dont show this popup again) - which causes never-ending popups of "A GameObject cannot have both a NetworkManager and NetworkObject assigned to it or any children under it.", until the editor is force closed via task manager.

**Comment by IAmTerrific** [comment]
Ah, the issue was my packages were too up-to-date for this sample project. Just need to fix that nesting issue *before* updating packages.

**Comment by Gabzee** [comment]
> 

Hey can you tell me how you fixed this issue it's showing me the same thing

**Comment by UnityJacob** [comment]
The project was built originally with an earlier version of Networking for GameObjects which allowed nested objects. I have a patch in the works that will address this . I will respond here when it is out.

**Comment by UnityJacob** [comment]
The Latest update should have addressed this, don't hesitate to open another ticket to let me know if you still experience issues!
