### ISSUE TITLE
Lobby without relay

### ISSUE THREAD

**Issue by jeffabenr** [Unity-Technologies/com.unity.services.samples.game-lobby#29]
good afternoon, how to create lobby without relay, forcing the use of both is horrible, it's as if the relay were the lobby itself and you have to use both together, so I should change from example to relaylobby, I need help on how to do, this would help a lot people who would like to host on their own server or other ways to use it. Could have an option to choose with relay or localhost or by ip

**Comment by UnityJacob** [comment]
Thanks for the feedback! You're in luck, as the next iteration of the Lobby sample will cleanly separate the Relay and Lobby Experiences. 
We will still use Relay for NGO, but it will be cleanly separated from the Lobby and the way it shares data.

**Comment by UnityJacob** [comment]
@jeffabenr Hello, I'm posting to let you know the sample has been updated. The Lobby list and interactions no longer rely on Relay at all, and should represent a much cleaner implementation.
