### ISSUE TITLE
Assets/AllScenes/com.unity.services.samples-2.game-lobby-main/Assets/Scripts/GameLobby/Lobby/LobbyManager.cs(32,9): error CS0246: The type or namespace name 'LobbyEventCallbacks' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by Gabzee** [Unity-Technologies/com.unity.services.samples.game-lobby#34]
I tried to install the lobby samples and it gave me this error, Assets/AllScenes/com.unity.services.samples-2.game-lobby-main/Assets/Scripts/GameLobby/Lobby/LobbyManager.cs(32,9): error CS0246: The type or namespace name 'LobbyEventCallbacks' could not be found (are you missing a using directive or an assembly reference?). and I know the lobbyeventcallbacks are important because it is referenced in many places please does anyone know how to fix it

**Comment by VKChiuselli** [comment]
Hi @Gabzee  , I'm having the same problem and I still didn't find a solution.

**Comment by Gabzee** [comment]
Yeah and I checked the lobby package and the lobbyeventcallback is there in
lobby,sdk,runtime i think but when I oppend the script  it was under #if
usg_beta_lobby_events and I don't really know what that means weather
that's where the problem is or from something else

**Comment by Gabzee** [comment]
I'll just wait I see if I can get some assistance from the unity people

**Comment by UnityJacob** [comment]
Hello! I'll take a look into this issue and see if i can reproduce!

**Comment by Gabzee** [comment]
Alright thanks

**Comment by VKChiuselli** [comment]
If you need help, I write my steps to get the error:
1.Open this lobby project
2.Export the whole project as package (In the editor: Assets-->Export Package).
3.Create a new project
4.Downloaded Relay and Lobby packages
5.Import the package created in point 2
And now you should get the error

**Comment by Gabzee** [comment]
For me I just imported the game-lobby sample and it just appeared tried
everything  icould but it refuses to go away

**Comment by UnityJacob** [comment]
Hello! Could you check your _Project Settings > Player > Script Compilation > **Scripting Define Symbols**_ and check if it contains: 

**UGS_BETA_LOBBY_EVENTS** and
**UGS_LOBBY_EVENTS**

They should be in ProjectSettings/ProjectSettings.asset in the project folder when you pull from Git. 

I'll add a note in the README to make sure others wont miss adding them for now. Hopefully this fixes it for you!

**Comment by UnityJacob** [comment]
![beta events](https://user-images.githubusercontent.com/57733156/204896616-19d1f1fd-b281-44c4-9800-b7cd8d2e02f0.PNG)
It should look like pic.

**Comment by Gabzee** [comment]
Aah God bless you my brother , that fixed the issue really thank you now I
can get back to work

**Comment by UnityJacob** [comment]
No Problem, I hope the updated readme will help mitigate this for other users until the beta is over :D.

**Comment by Gabzee** [comment]
Hey I was wondering if someone can help me out with this, I'm working on an
online multi-player game and I'm kind of stuck, I'm using the unity lobby
sample and what I want is for the player who is the server to be able to
choose which map that should be loaded and all players in the lobby are
sent to that scene. Basically like call of deuty mobile lobbys(rooms)

**Comment by Gabzee** [comment]
Hey can someone please help me out here, so Iteied installing the parrel
sync package on unity everything works well but when ever I try to open a
clone editor my unity hub doesn't allow me it says you can only run one
unity instance at a time I don't know what to do weather I was supposed to
do something before installing the package or something that allows unity
hub to run more than one instace of unity so please if anyone knows what I
can or should do please tell me. I have so many issues that are killing my
game
