### ISSUE TITLE
Bug in joining private lobby

### ISSUE THREAD

**Issue by MoProductions01** [Unity-Technologies/com.unity.services.samples.game-lobby#35]
I was working with the latest Lobby project but was unable to join a private lobby even though I was following along to the official Unity "How to set up Relay and Lobby" guide.  

After getting acknowledgement about the issue on Discord I fixed it by changing the "public void OnJoinButtonPressed()" function in JoinMenuUI.cs (line 70) to this:

`public void OnJoinButtonPressed()
{
    string selectedLobbyID = null;
    if (m_LocalLobbySelected != null)
    {
        selectedLobbyID = m_LocalLobbySelected.LobbyID.Value;
    }

    Manager.JoinLobby(selectedLobbyID, m_InputLobbyCode);
    m_LocalLobbySelected = null;
}`
``

What was going on is the original code would bail if "m_LocalLobbySelected == null" but when joining a private lobby that IS null and the async code down the line joins by lobby code instead of lobby id.  I can now get into the private lobby.

I know a pull request is supposed to be used for things like this but I'm new to the public git thing and don't think I have the permissions.  If I should do that let me know.

Thanks
-Mo

**Comment by UnityJacob** [comment]
Thanks for surfacing this! I'll implement this ASAP.
