### ISSUE TITLE
Cloned repository name casues invalid profile name if not renamed before use

### ISSUE THREAD

**Issue by ibytergj** [Unity-Technologies/com.unity.services.samples.game-lobby#41]
If someone clones this repo and opens it without renaming it, then the following error is generated when play is entered.

`AuthenticationException: Invalid profile name. The profile may only contain alphanumeric values, '-', '_', and must be no longer than 30 characters.`

This is due to the default project name of **com.unity.services.samples.game-lobby** being used to generate the profile name which becomes **player_com.unity.services.samples.game-lobby** which is 45 characters long.

It would be helpful if the offending project/profile name was part of the error message. I had to go digging for this.

Please consider adding a suggestion to the readme.md to have the project renamed after cloning.

**Comment by UnityJacob** [comment]
Since this is a feature of the authentication/parrelsync cloning system, I could just add a better system for creating unique clone profile names that excludes the bad characters. I'll add that now.

**Comment by UnityJacob** [comment]
I think I have fixed it in this Pull request
